# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainform.ui'
#
# Created: Fri Jun 24 10:35:52 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(555, 457)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.centralwidget)
        self.volumeSlider.setGeometry(QtCore.QRect(380, 59, 118, 41))
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.button_play = QtGui.QPushButton(self.centralwidget)
        self.button_play.setGeometry(QtCore.QRect(240, 50, 71, 61))
        self.button_play.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/playpause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_play.setIcon(icon)
        self.button_play.setIconSize(QtCore.QSize(78, 68))
        self.button_play.setObjectName(_fromUtf8("button_play"))
        self.button_previous = QtGui.QPushButton(self.centralwidget)
        self.button_previous.setGeometry(QtCore.QRect(190, 60, 41, 41))
        self.button_previous.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_previous.setIcon(icon1)
        self.button_previous.setIconSize(QtCore.QSize(41, 41))
        self.button_previous.setObjectName(_fromUtf8("button_previous"))
        self.button_next = QtGui.QPushButton(self.centralwidget)
        self.button_next.setGeometry(QtCore.QRect(320, 60, 41, 41))
        self.button_next.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_next.setIcon(icon2)
        self.button_next.setIconSize(QtCore.QSize(41, 41))
        self.button_next.setObjectName(_fromUtf8("button_next"))
        self.display_songname = QtGui.QLabel(self.centralwidget)
        self.display_songname.setGeometry(QtCore.QRect(0, 0, 551, 31))
        self.display_songname.setObjectName(_fromUtf8("display_songname"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.seekSlider = phonon.Phonon.SeekSlider(self.centralwidget)
        self.seekSlider.setGeometry(QtCore.QRect(10, 30, 531, 19))
        self.seekSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seekSlider.setAutoFillBackground(True)
        self.seekSlider.setIconVisible(False)
        self.seekSlider.setTracking(True)
        self.seekSlider.setObjectName(_fromUtf8("seekSlider"))
        self.playlist = QtGui.QListWidget(self.centralwidget)
        self.playlist.setGeometry(QtCore.QRect(20, 120, 511, 241))
        self.playlist.setObjectName(_fromUtf8("playlist"))
        self.checkShuffle = QtGui.QCheckBox(self.centralwidget)
        self.checkShuffle.setGeometry(QtCore.QRect(70, 70, 91, 21))
        self.checkShuffle.setObjectName(_fromUtf8("checkShuffle"))
        self.button_add_s = QtGui.QPushButton(self.centralwidget)
        self.button_add_s.setGeometry(QtCore.QRect(20, 370, 31, 27))
        self.button_add_s.setObjectName(_fromUtf8("button_add_s"))
        self.button_add_d = QtGui.QPushButton(self.centralwidget)
        self.button_add_d.setGeometry(QtCore.QRect(60, 370, 31, 27))
        self.button_add_d.setObjectName(_fromUtf8("button_add_d"))
        self.button_rmv_s = QtGui.QPushButton(self.centralwidget)
        self.button_rmv_s.setGeometry(QtCore.QRect(100, 370, 31, 27))
        self.button_rmv_s.setObjectName(_fromUtf8("button_rmv_s"))
        self.button_move_downdown = QtGui.QPushButton(self.centralwidget)
        self.button_move_downdown.setGeometry(QtCore.QRect(480, 370, 51, 27))
        self.button_move_downdown.setObjectName(_fromUtf8("button_move_downdown"))
        self.button_move_down = QtGui.QPushButton(self.centralwidget)
        self.button_move_down.setGeometry(QtCore.QRect(430, 370, 41, 27))
        self.button_move_down.setObjectName(_fromUtf8("button_move_down"))
        self.button_move_up = QtGui.QPushButton(self.centralwidget)
        self.button_move_up.setGeometry(QtCore.QRect(390, 370, 31, 27))
        self.button_move_up.setObjectName(_fromUtf8("button_move_up"))
        self.button_move_upup = QtGui.QPushButton(self.centralwidget)
        self.button_move_upup.setGeometry(QtCore.QRect(350, 370, 31, 27))
        self.button_move_upup.setObjectName(_fromUtf8("button_move_upup"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionAdd_Directory = QtGui.QAction(MainWindow)
        self.actionAdd_Directory.setObjectName(_fromUtf8("actionAdd_Directory"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuMenu.addAction(self.actionOpen)
        self.menuMenu.addAction(self.actionAdd_Directory)
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.display_songname.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.checkShuffle.setText(QtGui.QApplication.translate("MainWindow", "Shuffle", None, QtGui.QApplication.UnicodeUTF8))
        self.button_add_s.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.button_add_d.setText(QtGui.QApplication.translate("MainWindow", "Dir", None, QtGui.QApplication.UnicodeUTF8))
        self.button_rmv_s.setText(QtGui.QApplication.translate("MainWindow", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.button_move_downdown.setText(QtGui.QApplication.translate("MainWindow", "Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.button_move_down.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.button_move_up.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.button_move_upup.setText(QtGui.QApplication.translate("MainWindow", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Add Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Directory.setText(QtGui.QApplication.translate("MainWindow", "Add Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import phonon
##import resources_rc
